### ISSUE TITLE
download error occurred 

### ISSUE THREAD

**Issue by graywavve** [htdcx/code-push-server-go#6]
Hello,

An error occurred during the process, and I would appreciate it if you could check it.

After launching the app and making a GET request to:
/v0.1/public/codepush/update_check?deployment_key=c2d901a4-637f-11ef-a9ab-0242ac110004&app_version=1.0.0&client_unique_id=78a92c2d-761a-4389-9455-de84d58a7eeb

The response is as follows:
{
    "DownloadUrl": "d7310992-65e1-11ef-88c9-00d861f949ea.zip",
    "Description": "1.1.5.3",
    "IsAvailable": "true",
    "IsDisabled": "false",
    "TargetBinaryRange": "1.0.0",
    "PackageHash": "af56deb0da1b7ab34363844b7799462f3bb05f019032fb5dc9096928a5b3bbd7",
    "Label": "87",
    "PackageSize": "247409",
    "UpdateAppVersion": "false",
    "ShouldRunBinaryVersion": "false",
    "IsMandatory": "true"
}
It is displayed correctly.

However, when I checked the Android Logcat, there seems to be an issue with the bundle download. Logcat error:

....
Caused by: com.microsoft.codepush.react.CodePushMalformedDataException: The package has an invalid downloadUrl: d7310992-65e1-11ef-88c9-00d861f949ea.zip
...
Caused by: java.net.MalformedURLException: no protocol: d7310992-65e1-11ef-88c9-00d861f949ea.zip

Could you please check this?

**Comment by graywavve** [comment]
The server environment settings are as follows:

"CodePush": {
    "FileLocal": "local",
    "Local": {
        "SavePath": "./bundles"
    },
    "Aws": {
        "Endpoint": "",
        "Region": "",
        "S3ForcePathStyle": true,
        "KeyId": "",
        "Secret": "",
        "Bucket": ""
    },
    "Ftp": {
        "ServerUrl": "",
        "UserName": "",
        "Password": ""
    }
},
"UrlPrefix": "/",
"ResourceUrl": "",
"Port": ":8080",
"TokenExpireTime": 30

**Comment by htdcx** [comment]
@cuonggosu97 Add config: ResourceUrl

**Comment by cuonggosu97** [comment]
@htdcx Where do I config ResourceUrl? I added CodePushServerUrl to string.xml file

**Comment by cuonggosu97** [comment]
I added ResourceUrl to app.prod.json. But I still don't see the app updated.

**Comment by graywavve** [comment]
> I am having the same problem. Please let me know how you fix it. Thanks

Yes, in app.prod.json, I set ResourceUrl and Port to the path of the codepush server I use, and it was processed correctly.
