### ISSUE TITLE
Cannot Update with react-native-code-push

### ISSUE THREAD

**Issue by cuonggosu97** [htdcx/code-push-server-go#8]
Hi!

I am currently unable to update the application via codepush following your instructions. I have built my application release on Simulator and run the server on local host.

I have configured my Info.split file as follows
<key>CodePushDeploymentKey</key>
<string>98da623a-809c-11ef-9f79-ca3a63c0a2fa</string>
<key>CodePushServerURL</key>
<string>127.0.0.1:8080</string>

The CodePushDeploymentKey value I get when I execute the command:
./code-push-go app create_deployment -n <AppName> -dn <DeploymentName>

When I launch the application, the log in the terminal server does not call any request.

What do I need to do to be able to run like using code-push via Appcenter.
Thank!

**Comment by matiasblancor** [comment]
server must have ssl, otherwise react-native-code-push fails to check for new updates

**Comment by htdcx** [comment]
127.0.0.1:8080 is your phone ip，this is set server url
